### ISSUE TITLE
TypeError raised on "memote run"

### ISSUE THREAD

**Issue by bdelepine** [opencobra/memote#372]
#### Problem description

Hi guys,

I'm trying to follow the local workflow for using versionning and report features of memote. Unfortunately, `memote run` complains ("critical: Working with a repository requires a storage location.") and `memote run --location path_to_folder` crashes with a TypeError.

This seems to be related to #370 since both issues share the same traceback. Both 0.6.1 and develop branch are impacted.

Thank you for your help

#### Code Sample

```bash
$ memote run --location path_to_folder
Traceback (most recent call last):
  File "/home/XXX/.miniconda3/envs/gsm/bin/memote", line 11, in <module>
    sys.exit(cli())
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/memote/suite/cli/runner.py", line 140, in run
    manager = SQLResultManager(location)
TypeError: __init__() takes 1 positional argument but 2 were given
```

### Context

Please run the following code and paste the output inside the details
block.

```python
>>> memote.show_versions()
System Information
==================
OS                            Linux
OS-release    3.10.0-693.el7.x86_64
Python                        3.6.4

Package Versions
================
pip                           9.0.1
setuptools                   38.5.1
memote                        0.6.1
cobra                        0.11.3
future                       0.16.0
swiglpk                       1.4.4
optlang                       1.3.0
ruamel.yaml                 0.14.12
pandas                       0.22.0
numpy                        1.14.1
click                           6.7
pytest                        3.4.2
Jinja2                         2.10
jinja2-ospath                 0.2.1
cookiecutter                  1.6.0
>>> memote.__version__
'0.6.1'
```

**Comment by Midnighter** [comment]
Hey @bdelepine, thanks for trying that out! I'll work on a fix right now but please be aware that we're still upgrading the history report (which integrates nicely with your repository) and the different workflows required plus the automated testing.

So I'll get `memote run` to work inside of a repository now but my expectation for everything to work properly (`memote new`, `memote online`, `memote save`, `memote history`, and `memote report history`) is in two weeks.

**Comment by bdelepine** [comment]
Thank you for your quick answer.
So... no more creating issues in the next two weeks? :)

I can wait to have a fully functional version, no problem. BTW, I'm not interested about the GitHub integration (we don't use GitHub), but for anything else I would be happy to help (feedback, tests, documentation).

**Comment by Midnighter** [comment]
No, please keep informing us about any problems that you come across. I just wanted to set your expectations about things probably not fully working until after that time ;)

**Comment by ChristianLieven** [comment]
Hey @bdelepine try out the current devel branch. We've fixed the TypeError with https://github.com/opencobra/memote/pull/367

**Comment by bdelepine** [comment]
Hi @ChristianLieven, I already tried following the instructions in the documentation (git clone, then pip local install) and double-checked with a `pip install git+https://github.com/opencobra/memote.git@develop` in a dedicated environment. The problem persists. But maybe I don't get how to install the dev branch: `pip show memote` tells me that the version is 0.6.1. Am I messing something?

@Midnighter Great! No worries: I can work with a partially working version-and-report tool for now.

**Comment by Midnighter** [comment]
0.6.2 should be on PyPi any minute now. Let me know if there are any more problems.

**Comment by bdelepine** [comment]
Problem solved. Thanks!
